model:
  name: "CTEFNet"
  mode: "pretrain"
  dim: 256
  head: 4
  depth: 6
  dim_feedforward: 256
  dropout: 0
  load_pretrain: False
data:
  predictor: [ 'thetao_5', 'thetao_wmean', 'tauu', 'tauv', 'uo_5', 'vo_5', 'psl', 'mlotst', 'sos'] 

  predictand: ['nino34']

  train_models: [ 'ACCESS-CM2', 'ACCESS-ESM1-5', 'CESM2', 'CESM2-WACCM', 'CNRM-CM6-1', 'E3SM-1-0', 'EC-Earth3', 'FGOALS-f3-L', 'FGOALS-g3', 'IPSL-CM6A-LR', 'MIROC6', 'MRI-ESM2-0', 'NorESM2-MM', 'UKESM1-0-LL', 'CAS-ESM2-0', 'CanESM5', 'CMCC-ESM2']
  train_period: [ 2015,2100 ] #1850-2100

  valid_models: [ 'ORAS5' ]
  valid_period: [ 1958, 1978 ]

  image_size: [ 120, 180 ]
  input_region: [ 0, 120, 0, 180 ]
  target_region: [ 54, 64, 95, 120 ]
  obs_time: 12
  pred_type: 'series'  # 'series'
  pred_time: 24
  train_batch_size: 8 # 16
  valid_batch_size: 32
  channel_erasing: 0.2 #0.2
  frame_erasing: 0.2 #0.2
optimizer:
  name: "adam"
  epoch: 40
  lr_max: 0.00002
  lr_min: 0.0000001
  warm_milestone: 1000 #1000
  annealing_index: 0.5
  penalty: 0.1 #0.1
  loss:
    lambda1: 1
    lambda2: 0.1
    lambda3: 0
summary:
  summary_dir: "./summary/checkpoints"
  stage: 1
  print_freq: 100 # 10
  eval_freq: 300 # 500
  best_result: -100
  patient: 10
  current_patient: 0
  leading_mon: 0
  corr_array: []
